import {
    PIECE_COLOR_BLACK,
    PIECE_COLOR_WHITE,
    PIECE_TYPE_BOAT,
    PIECE_TYPE_TRANSFORM_FISH,
    PIECE_TYPE_GENERAL,
    PIECE_TYPE_QUEEN,
    PIECE_TYPE_KING,
    PIECE_TYPE_HORSE,
    PIECE_TYPE_FISH,
    KhmerChess,
    COLOR_NAMES,
    COLOR_NAMES_ENGLISH,
    PIECE_NAMES,
    PIECE_NAMES_ENGLISH,
    EMPTY_PIECE,
    PIECE_COLOR_EMPTY,
    BOARD_SEPARATOR,
    ROW_NUMBER,
    VERTICAL_NOTE_LETTERS_ENGLISH,
    HORIZONTAL_NOTE_LETTERS_ENGLISH,
    VERTICAL_NOTE_LETTERS,
    HORIZONTAL_NOTE_LETTERS,
    HORIZONTAL_CODE_LETTERS,
    ROW_FIRST_INDEX,
    ROW_LAST_INDEX,
    CELL_COUNT,
    STRING_COUNT,
    DEFAULT_BOARD_STR,
    NOT_SET,
    PIECE_FLAG_KILL,
    PIECE_FLAG_JUMP,
    PIECE_FLAG_UPGRADE,
    PIECE_FLAG_START_COUNTING,
    EVENT_FLAG_ATTACK,
    EVENT_FLAG_WIN,
    EVENT_FLAG_DRAW,
    EVENT_FLAG_START_COUNTING,
    EVENT_FLAG_COUNTING_UP,
    EVENT_FLAG_COUNT_UP_OUT,
    EVENT_FLAG_MOVING,
} from 'khmer-chess';

export default class KhmerChessProps {
    static PIECE_COLOR_WHITE = PIECE_COLOR_WHITE;
    static PIECE_COLOR_BLACK = PIECE_COLOR_BLACK;
    static COLOR_NAMES = COLOR_NAMES;
    static COLOR_NAMES_ENGLISH = COLOR_NAMES_ENGLISH;
    static PIECE_TYPE_BOAT = PIECE_TYPE_BOAT;
    static PIECE_TYPE_HORSE = PIECE_TYPE_HORSE;
    static PIECE_TYPE_GENERAL = PIECE_TYPE_GENERAL;
    static PIECE_TYPE_KING = PIECE_TYPE_KING;
    static PIECE_TYPE_QUEEN = PIECE_TYPE_QUEEN;
    static PIECE_TYPE_FISH = PIECE_TYPE_FISH;
    static PIECE_TYPE_TRANSFORM_FISH = PIECE_TYPE_TRANSFORM_FISH;
    static PIECE_NAMES = PIECE_NAMES;
    static PIECE_NAMES_ENGLISH = PIECE_NAMES_ENGLISH;
    static EMPTY_PIECE = EMPTY_PIECE;
    static PIECE_COLOR_EMPTY = PIECE_COLOR_EMPTY;
    static BOARD_SEPARATOR = BOARD_SEPARATOR;
    static ROW_NUMBER = ROW_NUMBER;
    static ROW_FIRST_INDEX = ROW_FIRST_INDEX;
    static ROW_LAST_INDEX = ROW_LAST_INDEX;
    static CELL_COUNT = CELL_COUNT;
    static HORIZONTAL_CODE_LETTERS = HORIZONTAL_CODE_LETTERS;
    static HORIZONTAL_NOTE_LETTERS = HORIZONTAL_NOTE_LETTERS;
    static VERTICAL_NOTE_LETTERS = VERTICAL_NOTE_LETTERS;
    static HORIZONTAL_NOTE_LETTERS_ENGLISH = HORIZONTAL_NOTE_LETTERS_ENGLISH;
    static VERTICAL_NOTE_LETTERS_ENGLISH = VERTICAL_NOTE_LETTERS_ENGLISH;
    static STRING_COUNT = STRING_COUNT;
    static DEFAULT_BOARD_STR = DEFAULT_BOARD_STR;
    static NOT_SET = NOT_SET;
    static PIECE_FLAG_KILL = PIECE_FLAG_KILL;
    static PIECE_FLAG_JUMP = PIECE_FLAG_JUMP;
    static PIECE_FLAG_UPGRADE = PIECE_FLAG_UPGRADE;
    static PIECE_FLAG_START_COUNTING = PIECE_FLAG_START_COUNTING;
    static EVENT_FLAG_ATTACK = EVENT_FLAG_ATTACK;
    static EVENT_FLAG_WIN = EVENT_FLAG_WIN;
    static EVENT_FLAG_DRAW = EVENT_FLAG_DRAW;
    static EVENT_FLAG_START_COUNTING = EVENT_FLAG_START_COUNTING;
    static EVENT_FLAG_COUNTING_UP = EVENT_FLAG_COUNTING_UP;
    static EVENT_FLAG_COUNT_UP_OUT = EVENT_FLAG_COUNT_UP_OUT;
    static EVENT_FLAG_MOVING = EVENT_FLAG_MOVING;
    static KhmerChess = KhmerChess;
}

/*
 * Copyright (c) 2021, K4us
 * Author: Raksa Eng <eng.raksa@gmail.com>, K4us Net <k4us.net@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 **/